project:
  type: website

website:
  title: "Welcome to my blog!"
  navbar:
    right:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/rebanta-aryal
      - icon: github
        href: https://github.com/reban87
      - icon: gear-fill
        href: https://linktr.ee/rebanaryal

format:
  html:
    theme: lux
    css: styles.css